### PR TITLE
Fixed compatibility issue with Elementor v3.26

### PR DESCRIPTION
**Pull request by girishpanchal30**
### Summary

I have updated the Elementor Typography implementation to reflect the latest changes.  
For more details on the updates in version 3.26, check the discussion here: [Elementor v3.26 Beta Release](https://github.com/orgs/elementor/discussions/29403).

### Typography Changes
https://developers.elementor.com/docs/deprecations/complex-example/

Close https://github.com/Codeinwp/themeisle-companion/issues/882

### CODE REVIEW

**Review by Soare-Robert-Daniel — APPROVED** [review]

**Comment by rodica-andronache** [comment]
@girishpanchal30 can you please share the build, so I can test? Thank you!

**Comment by girishpanchal30** [comment]
@vytisbulkevicius @selul Is there a way to test this PR? I’ve tested it locally using the composer patch apply method mentioned below.

```
"extra": {
    "patches": {
        "codeinwp/elementor-extra-widgets": [
            "patches/tc-882.patch"
        ]
    }
 }
```

If testing isn’t possible, please merge this PR so I can update the composer package for the `themeisle-companion` plugin.

Thanks!

**Comment by Soare-Robert-Daniel** [comment]
@girishpanchal30 I think in your current setup you can run `npm run dist` on `themeisle-companion` with that patch you applied. It should bundle everything in the created ZIP files on `artifact` folder.

**Comment by selul** [comment]
@girishpanchal30 to remove this back and forth, you can integrate the library directly into the plugin into a folder of your choice. 

This repo is not used in any other product atm.

**Comment by girishpanchal30** [comment]
@selul I have moved the `elementor-extra-widgets` folder into the plugin as part of this [PR](https://github.com/Codeinwp/themeisle-companion/pull/883).

However, I’ve now noticed a fatal error in the `themeisle-content-forms` package, which I didn't notice before.

```
[18-Dec-2024 09:16:42 UTC] PHP Fatal error:  Uncaught Error: Class "Elementor\Core\Schemes\Color" not found in /var/www/html/codeinwp/wp-content/plugins/themeisle-companion/vendor/codeinwp/themeisle-content-forms/includes/widgets-admin/elementor/elementor_widget_base.php:307
```

Should I apply the same changes to the `themeisle-content-forms` package as well?

**Comment by selul** [comment]
yes, please.

**Comment by girishpanchal30** [comment]
@rodica-andronache I've fixed the issue this [PR](https://github.com/Codeinwp/themeisle-companion/pull/883
), Please ignore this PR

**Pull request closed without merging**
